apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # URL сервера Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    # Твой email для уведомлений (замени на свой!)
    email: sergei.v.filippov@gmail.com
    # Секрет, где будет храниться приватный ключ аккаунта
    privateKeySecretRef:
      name: letsencrypt-prod
    # Способ подтверждения владения доменом (HTTP-01)
    solvers:
    - http01:
        ingress:
          class: nginx