apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt server URL 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sergei.v.filippov@gmail.com
    # Secret where the account's private key will be stored
    privateKeySecretRef:
      name: letsencrypt-prod
    # Method of confirming domain ownership (HTTP-01)
    solvers:
    - http01:
        ingress:
          class: nginx