apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    # Critical: Matches the 'serviceMonitorSelector' in Prometheus Operator
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend # Matches the label in service.yaml
  endpoints:
  - port: http # Refers to the port name in service.yaml
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default